# Site settings
title: iBlog
url: "http://Chensheng1996.github.io"    # the protocol and hostname of your site, eg. `http://laobubu.github.io`
#baseurl: "/jekyll-theme-EasyBook" # the prefix of your site uri, eg. `"/jekyll-theme-EasyBook"` or empty string `""`
timezone: Asia/Shanghai
description: >
  One or more sentences introducing this blog.

# Your information
email: 1791823620@qq.com
author: Chensheng
# avatar: "//www.gravatar.com/avatar/1791823620@qq.com_md5?d=mm&s=135"
avatar: "img/headImg.jpg"
profile: 用心、专注
#twitter_username: twitter_username
#github_username:  github_username
profile_links:
  Email: "mailto:1791823620@qq.com"
  GitHub: "https://github.com/Chensheng1996/"
  # You can add more profile links above, or edit _includes/sidebar.html 

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
#disqus_shortname: xxx   # get one: https://disqus.com/admin/signup/
#duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/

excerpt_separator: <!--more-->

header:
  links:             # Links on the header. Link to in-site page with a slash as prefix
    目录: /category/
    关于: /about/

permalink: /archivers/:title
plugins:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

# https://jekyllrb.com/docs/configuration/#precedence
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax
